/*
 * Generated by gdbus-codegen 2.42.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __GS_SHELL_SEARCH_PROVIDER_GENERATED_H__
#define __GS_SHELL_SEARCH_PROVIDER_GENERATED_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.gnome.Shell.SearchProvider2 */

#define GS_TYPE_SHELL_SEARCH_PROVIDER2 (gs_shell_search_provider2_get_type ())
#define GS_SHELL_SEARCH_PROVIDER2(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GS_TYPE_SHELL_SEARCH_PROVIDER2, GsShellSearchProvider2))
#define GS_IS_SHELL_SEARCH_PROVIDER2(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GS_TYPE_SHELL_SEARCH_PROVIDER2))
#define GS_SHELL_SEARCH_PROVIDER2_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), GS_TYPE_SHELL_SEARCH_PROVIDER2, GsShellSearchProvider2Iface))

struct _GsShellSearchProvider2;
typedef struct _GsShellSearchProvider2 GsShellSearchProvider2;
typedef struct _GsShellSearchProvider2Iface GsShellSearchProvider2Iface;

struct _GsShellSearchProvider2Iface
{
  GTypeInterface parent_iface;

  gboolean (*handle_activate_result) (
    GsShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_Result,
    const gchar *const *arg_Terms,
    guint arg_Timestamp);

  gboolean (*handle_get_initial_result_set) (
    GsShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *arg_Terms);

  gboolean (*handle_get_result_metas) (
    GsShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *arg_Results);

  gboolean (*handle_get_subsearch_result_set) (
    GsShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *arg_PreviousResults,
    const gchar *const *arg_Terms);

  gboolean (*handle_launch_search) (
    GsShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *arg_Terms,
    guint arg_Timestamp);

};

GType gs_shell_search_provider2_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *gs_shell_search_provider2_interface_info (void);
guint gs_shell_search_provider2_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void gs_shell_search_provider2_complete_get_initial_result_set (
    GsShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *Results);

void gs_shell_search_provider2_complete_get_subsearch_result_set (
    GsShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *Results);

void gs_shell_search_provider2_complete_get_result_metas (
    GsShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation,
    GVariant *Metas);

void gs_shell_search_provider2_complete_activate_result (
    GsShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation);

void gs_shell_search_provider2_complete_launch_search (
    GsShellSearchProvider2 *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void gs_shell_search_provider2_call_get_initial_result_set (
    GsShellSearchProvider2 *proxy,
    const gchar *const *arg_Terms,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean gs_shell_search_provider2_call_get_initial_result_set_finish (
    GsShellSearchProvider2 *proxy,
    gchar ***out_Results,
    GAsyncResult *res,
    GError **error);

gboolean gs_shell_search_provider2_call_get_initial_result_set_sync (
    GsShellSearchProvider2 *proxy,
    const gchar *const *arg_Terms,
    gchar ***out_Results,
    GCancellable *cancellable,
    GError **error);

void gs_shell_search_provider2_call_get_subsearch_result_set (
    GsShellSearchProvider2 *proxy,
    const gchar *const *arg_PreviousResults,
    const gchar *const *arg_Terms,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean gs_shell_search_provider2_call_get_subsearch_result_set_finish (
    GsShellSearchProvider2 *proxy,
    gchar ***out_Results,
    GAsyncResult *res,
    GError **error);

gboolean gs_shell_search_provider2_call_get_subsearch_result_set_sync (
    GsShellSearchProvider2 *proxy,
    const gchar *const *arg_PreviousResults,
    const gchar *const *arg_Terms,
    gchar ***out_Results,
    GCancellable *cancellable,
    GError **error);

void gs_shell_search_provider2_call_get_result_metas (
    GsShellSearchProvider2 *proxy,
    const gchar *const *arg_Results,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean gs_shell_search_provider2_call_get_result_metas_finish (
    GsShellSearchProvider2 *proxy,
    GVariant **out_Metas,
    GAsyncResult *res,
    GError **error);

gboolean gs_shell_search_provider2_call_get_result_metas_sync (
    GsShellSearchProvider2 *proxy,
    const gchar *const *arg_Results,
    GVariant **out_Metas,
    GCancellable *cancellable,
    GError **error);

void gs_shell_search_provider2_call_activate_result (
    GsShellSearchProvider2 *proxy,
    const gchar *arg_Result,
    const gchar *const *arg_Terms,
    guint arg_Timestamp,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean gs_shell_search_provider2_call_activate_result_finish (
    GsShellSearchProvider2 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean gs_shell_search_provider2_call_activate_result_sync (
    GsShellSearchProvider2 *proxy,
    const gchar *arg_Result,
    const gchar *const *arg_Terms,
    guint arg_Timestamp,
    GCancellable *cancellable,
    GError **error);

void gs_shell_search_provider2_call_launch_search (
    GsShellSearchProvider2 *proxy,
    const gchar *const *arg_Terms,
    guint arg_Timestamp,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean gs_shell_search_provider2_call_launch_search_finish (
    GsShellSearchProvider2 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean gs_shell_search_provider2_call_launch_search_sync (
    GsShellSearchProvider2 *proxy,
    const gchar *const *arg_Terms,
    guint arg_Timestamp,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define GS_TYPE_SHELL_SEARCH_PROVIDER2_PROXY (gs_shell_search_provider2_proxy_get_type ())
#define GS_SHELL_SEARCH_PROVIDER2_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GS_TYPE_SHELL_SEARCH_PROVIDER2_PROXY, GsShellSearchProvider2Proxy))
#define GS_SHELL_SEARCH_PROVIDER2_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), GS_TYPE_SHELL_SEARCH_PROVIDER2_PROXY, GsShellSearchProvider2ProxyClass))
#define GS_SHELL_SEARCH_PROVIDER2_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GS_TYPE_SHELL_SEARCH_PROVIDER2_PROXY, GsShellSearchProvider2ProxyClass))
#define GS_IS_SHELL_SEARCH_PROVIDER2_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GS_TYPE_SHELL_SEARCH_PROVIDER2_PROXY))
#define GS_IS_SHELL_SEARCH_PROVIDER2_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GS_TYPE_SHELL_SEARCH_PROVIDER2_PROXY))

typedef struct _GsShellSearchProvider2Proxy GsShellSearchProvider2Proxy;
typedef struct _GsShellSearchProvider2ProxyClass GsShellSearchProvider2ProxyClass;
typedef struct _GsShellSearchProvider2ProxyPrivate GsShellSearchProvider2ProxyPrivate;

struct _GsShellSearchProvider2Proxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  GsShellSearchProvider2ProxyPrivate *priv;
};

struct _GsShellSearchProvider2ProxyClass
{
  GDBusProxyClass parent_class;
};

GType gs_shell_search_provider2_proxy_get_type (void) G_GNUC_CONST;

void gs_shell_search_provider2_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
GsShellSearchProvider2 *gs_shell_search_provider2_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
GsShellSearchProvider2 *gs_shell_search_provider2_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void gs_shell_search_provider2_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
GsShellSearchProvider2 *gs_shell_search_provider2_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
GsShellSearchProvider2 *gs_shell_search_provider2_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define GS_TYPE_SHELL_SEARCH_PROVIDER2_SKELETON (gs_shell_search_provider2_skeleton_get_type ())
#define GS_SHELL_SEARCH_PROVIDER2_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GS_TYPE_SHELL_SEARCH_PROVIDER2_SKELETON, GsShellSearchProvider2Skeleton))
#define GS_SHELL_SEARCH_PROVIDER2_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), GS_TYPE_SHELL_SEARCH_PROVIDER2_SKELETON, GsShellSearchProvider2SkeletonClass))
#define GS_SHELL_SEARCH_PROVIDER2_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GS_TYPE_SHELL_SEARCH_PROVIDER2_SKELETON, GsShellSearchProvider2SkeletonClass))
#define GS_IS_SHELL_SEARCH_PROVIDER2_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GS_TYPE_SHELL_SEARCH_PROVIDER2_SKELETON))
#define GS_IS_SHELL_SEARCH_PROVIDER2_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GS_TYPE_SHELL_SEARCH_PROVIDER2_SKELETON))

typedef struct _GsShellSearchProvider2Skeleton GsShellSearchProvider2Skeleton;
typedef struct _GsShellSearchProvider2SkeletonClass GsShellSearchProvider2SkeletonClass;
typedef struct _GsShellSearchProvider2SkeletonPrivate GsShellSearchProvider2SkeletonPrivate;

struct _GsShellSearchProvider2Skeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  GsShellSearchProvider2SkeletonPrivate *priv;
};

struct _GsShellSearchProvider2SkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType gs_shell_search_provider2_skeleton_get_type (void) G_GNUC_CONST;

GsShellSearchProvider2 *gs_shell_search_provider2_skeleton_new (void);


G_END_DECLS

#endif /* __GS_SHELL_SEARCH_PROVIDER_GENERATED_H__ */
